/**
 * TealTiger SDK v1.1.x - Correlation IDs and Tracing Examples
 * 
 * Demonstrates how to use ExecutionContext for end-to-end request tracing:
 * - Creating execution context with auto-generated correlation_id
 * - Creating execution context with custom correlation_id
 * - Propagating context through multiple TealTiger operations
 * - Querying audit logs by correlation_id
 * - Distributed tracing integration with OpenTelemetry (trace_id, span_id)
 * - HTTP header propagation using fromHeaders() and toHeaders()
 * 
 * ExecutionContext enables comprehensive traceability across all TealTiger
 * components and external systems for incident investigation and compliance.
 */

import { TealEngine } from '../src/core/engine/TealEngine';
import { TealGuard } from '../src/core/guard/TealGuard';
import { TealOpenAI } from '../src/clients/TealOpenAI';
import { TealAudit, ConsoleOutput } from '../src/core/audit/TealAudit';
import { ContextManager } from '../src/core/context/ContextManager';
import { ExecutionContext } from '../src/core/context/ExecutionContext';
import { PolicyMode, DecisionAction } from '../src/core/engine/types';
import { RedactionLevel } from '../src/core/audit/redaction';

/**
 * Example 1: Auto-Generated Correlation ID
 * 
 * Shows how to create an ExecutionContext with auto-generated correlation_id.
 * The correlation_id is a UUID v4 generated using cryptographically random values.
 */
async function example1_AutoGeneratedCorrelationId() {
  console.log('\n=== Example 1: Auto-Generated Correlation ID ===\n');

  // Create context without providing correlation_id - it will be auto-generated
  const context = ContextManager.createContext({
    tenant_id: 'acme-corp',
    application: 'customer-support',
    environment: 'production'
  });

  console.log('Created ExecutionContext with auto-generated correlation_id:');
  console.log('  correlation_id:', context.correlation_id);
  console.log('  tenant_id:', context.tenant_id);
  console.log('  application:', context.application);
  console.log('  environment:', context.environment);
  console.log('  created_at:', context.created_at);

  console.log('\nBenefits:');
  console.log('   - No manual ID management required');
  console.log('   - Cryptographically random UUID v4');
  console.log('   - Guaranteed uniqueness across requests');
  console.log('   - Automatic timestamp tracking');
}


/**
 * Example 2: Custom Correlation ID
 * 
 * Shows how to create an ExecutionContext with a custom correlation_id.
 * Useful when integrating with existing tracing systems or when you need
 * to use a specific ID format.
 */
async function example2_CustomCorrelationId() {
  console.log('\n=== Example 2: Custom Correlation ID ===\n');

  // Create context with custom correlation_id
  const customId = 'req-2024-12345-abcdef';
  const context = ContextManager.createContext({
    correlation_id: customId,
    tenant_id: 'acme-corp',
    application: 'api-gateway',
    environment: 'production'
  });

  console.log('Created ExecutionContext with custom correlation_id:');
  console.log('  correlation_id:', context.correlation_id);
  console.log('  Custom format:', context.correlation_id === customId);
  console.log('  tenant_id:', context.tenant_id);

  console.log('\nUse Cases:');
  console.log('   - Integration with existing tracing systems');
  console.log('   - Custom ID format requirements');
  console.log('   - Correlation with external request IDs');
  console.log('   - Legacy system compatibility');
}

/**
 * Example 3: Propagating Context Through Multiple Operations
 * 
 * Shows how ExecutionContext propagates through TealEngine, TealGuard, and
 * provider clients, maintaining the same correlation_id for end-to-end tracing.
 */
async function example3_ContextPropagation() {
  console.log('\n=== Example 3: Context Propagation Through Multiple Operations ===\n');

  // Step 1: Create initial context
  const context = ContextManager.createContext({
    tenant_id: 'acme-corp',
    application: 'customer-support',
    environment: 'production',
    agent_purpose: 'ticket_resolution',
    workflow_id: 'support-workflow-v1',
    run_id: 'run-12345'
  });

  console.log('Step 1: Created initial ExecutionContext');
  console.log('  correlation_id:', context.correlation_id);
  console.log('  workflow_id:', context.workflow_id);
  console.log('  run_id:', context.run_id);

  // Step 2: Initialize TealEngine
  const engine = new TealEngine(
    {
      tools: {
        customer_data_read: { allowed: true },
        file_delete: { allowed: false }
      },
      identity: {
        agentId: 'support-001',
        role: 'customer-support',
        permissions: ['read:customer_data']
      }
    },
    {
      mode: { default: PolicyMode.ENFORCE }
    }
  );

  // Step 3: Evaluate policy with context
  console.log('\nStep 2: Evaluating policy with TealEngine...');
  const policyDecision = engine.evaluateWithMode(
    {
      agentId: 'support-001',
      action: 'tool.execute',
      tool: 'customer_data_read'
    },
    context
  );

  console.log('  Decision:', policyDecision.action);
  console.log('  correlation_id:', policyDecision.correlation_id);
  console.log('  Same as original:', policyDecision.correlation_id === context.correlation_id);

  // Step 4: Initialize TealGuard
  const guard = new TealGuard();

  // Step 5: Check content with context
  console.log('\nStep 3: Checking content with TealGuard...');
  const guardDecision = await guard.check(
    'Read customer data for ticket #12345',
    context
  );

  console.log('  Decision:', guardDecision.action);
  console.log('  correlation_id:', guardDecision.correlation_id);
  console.log('  Same as original:', guardDecision.correlation_id === context.correlation_id);

  console.log('\nContext Propagation Complete!');
  console.log('   All operations share correlation_id:', context.correlation_id);
  console.log('   All decisions can be traced back to the original request');
  console.log('   All audit events will have the same correlation_id');
}


/**
 * Example 4: Querying Audit Logs by Correlation ID
 * 
 * Shows how to use correlation_id to query audit logs and trace all events
 * related to a specific request across all components.
 */
async function example4_QueryAuditLogsByCorrelationId() {
  console.log('\n=== Example 4: Querying Audit Logs by Correlation ID ===\n');

  // Initialize audit with console output
  const audit = new TealAudit({
    outputs: [new ConsoleOutput()],
    config: {
      input_redaction: RedactionLevel.HASH,
      output_redaction: RedactionLevel.HASH,
      detect_pii: true
    }
  });

  // Create context
  const context = ContextManager.createContext({
    tenant_id: 'acme-corp',
    application: 'customer-support',
    environment: 'production'
  });

  console.log('Logging events with correlation_id:', context.correlation_id);

  // Log multiple events with the same correlation_id
  console.log('\nEvent 1: Policy Evaluation');
  audit.log(
    {
      schema_version: '1.0.0',
      event_type: 'policy.evaluation' as any,
      timestamp: new Date().toISOString(),
      correlation_id: context.correlation_id,
      action: DecisionAction.ALLOW,
      risk_score: 25,
      mode: PolicyMode.ENFORCE,
      policy_id: 'tools.customer_data_read',
      policy_version: '1.0.0'
    },
    context
  );

  console.log('\nEvent 2: Guardrail Check');
  audit.log(
    {
      schema_version: '1.0.0',
      event_type: 'guardrail.check' as any,
      timestamp: new Date().toISOString(),
      correlation_id: context.correlation_id,
      action: DecisionAction.ALLOW,
      risk_score: 15,
      mode: PolicyMode.ENFORCE,
      policy_id: 'content.pii',
      policy_version: '1.0.0'
    },
    context
  );

  console.log('\nEvent 3: LLM Request');
  audit.log(
    {
      schema_version: '1.0.0',
      event_type: 'llm.request' as any,
      timestamp: new Date().toISOString(),
      correlation_id: context.correlation_id,
      provider: 'openai',
      model: 'gpt-4',
      safe_inputs: {
        hash: 'sha256:abc123...',
        size: 1024
      }
    },
    context
  );

  console.log('\nAudit Log Query:');
  console.log('   Query: SELECT * FROM audit_events WHERE correlation_id =', context.correlation_id);
  console.log('   Result: All 3 events returned');
  console.log('   Use case: Incident investigation, compliance reporting, debugging');
}

/**
 * Example 5: Distributed Tracing with OpenTelemetry
 * 
 * Shows how to integrate TealTiger with OpenTelemetry for distributed tracing
 * using trace_id and span_id fields.
 */
async function example5_OpenTelemetryIntegration() {
  console.log('\n=== Example 5: Distributed Tracing with OpenTelemetry ===\n');

  // Simulate OpenTelemetry trace context
  const otelTraceId = '4bf92f3577b34da6a3ce929d0e0e4736'; // 32 hex chars
  const otelSpanId = '00f067aa0ba902b7'; // 16 hex chars

  console.log('OpenTelemetry Trace Context:');
  console.log('  trace_id:', otelTraceId);
  console.log('  span_id:', otelSpanId);

  // Create context with OpenTelemetry trace information
  const context = ContextManager.createContext({
    trace_id: otelTraceId,
    span_id: otelSpanId,
    tenant_id: 'acme-corp',
    application: 'distributed-system',
    environment: 'production'
  });

  console.log('\nCreated ExecutionContext with OpenTelemetry integration:');
  console.log('  correlation_id:', context.correlation_id);
  console.log('  trace_id:', context.trace_id);
  console.log('  span_id:', context.span_id);

  // Initialize TealEngine
  const engine = new TealEngine(
    {
      tools: {
        api_call: { allowed: true }
      },
      identity: {
        agentId: 'api-agent-001',
        role: 'api-gateway',
        permissions: ['call:api']
      }
    },
    {
      mode: { default: PolicyMode.ENFORCE }
    }
  );

  // Evaluate policy - trace_id and span_id propagate
  const decision = engine.evaluateWithMode(
    {
      agentId: 'api-agent-001',
      action: 'tool.execute',
      tool: 'api_call'
    },
    context
  );

  console.log('\nDecision with OpenTelemetry context:');
  console.log('  correlation_id:', decision.correlation_id);
  console.log('  trace_id:', decision.trace_id);
  console.log('  span_id:', decision.span_id);

  console.log('\nOpenTelemetry Integration:');
  console.log('   - TealTiger decisions include trace_id and span_id');
  console.log('   - Correlate TealTiger events with APM traces');
  console.log('   - Visualize security decisions in distributed traces');
  console.log('   - Compatible with Jaeger, Zipkin, Datadog, New Relic');
}

/**
 * Example 6: HTTP Header Propagation
 * 
 * Shows how to propagate ExecutionContext across HTTP boundaries using
 * fromHeaders() and toHeaders() methods.
 */
async function example6_HTTPHeaderPropagation() {
  console.log('\n=== Example 6: HTTP Header Propagation ===\n');

  // Scenario: Incoming HTTP request with tracing headers
  console.log('Scenario: Incoming HTTP request\n');

  const incomingHeaders = {
    'x-correlation-id': 'req-upstream-12345',
    'traceparent': '00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01',
    'x-tenant-id': 'acme-corp',
    'x-application': 'api-gateway',
    'x-environment': 'production'
  };

  console.log('Incoming HTTP Headers:');
  for (const [key, value] of Object.entries(incomingHeaders)) {
    console.log('  ' + key + ':', value);
  }

  // Extract context from headers
  const context = ContextManager.fromHeaders(incomingHeaders);

  console.log('\nExtracted ExecutionContext:');
  console.log('  correlation_id:', context.correlation_id);
  console.log('  trace_id:', context.trace_id);
  console.log('  tenant_id:', context.tenant_id);
  console.log('  application:', context.application);
  console.log('  environment:', context.environment);

  // Process request with TealTiger
  const engine = new TealEngine(
    {
      tools: {
        downstream_api: { allowed: true }
      },
      identity: {
        agentId: 'gateway-001',
        role: 'api-gateway',
        permissions: ['call:downstream']
      }
    },
    {
      mode: { default: PolicyMode.ENFORCE }
    }
  );

  const decision = engine.evaluateWithMode(
    {
      agentId: 'gateway-001',
      action: 'tool.execute',
      tool: 'downstream_api'
    },
    context
  );

  console.log('\nPolicy Decision:');
  console.log('  action:', decision.action);
  console.log('  correlation_id:', decision.correlation_id);

  // Convert context to headers for downstream request
  const outgoingHeaders = ContextManager.toHeaders(context);

  console.log('\nOutgoing HTTP Headers (for downstream service):');
  for (const [key, value] of Object.entries(outgoingHeaders)) {
    console.log('  ' + key + ':', value);
  }

  console.log('\nHTTP Header Propagation:');
  console.log('   - Extract context from incoming requests');
  console.log('   - Preserve correlation_id across service boundaries');
  console.log('   - Propagate context to downstream services');
  console.log('   - Enable end-to-end distributed tracing');
}


/**
 * Example 7: Nested Operations with Span Hierarchy
 * 
 * Shows how to use span_id and parent_span_id to create a hierarchy of
 * operations for detailed tracing.
 */
async function example7_NestedOperationsWithSpans() {
  console.log('\n=== Example 7: Nested Operations with Span Hierarchy ===\n');

  // Create root context
  const rootContext = ContextManager.createContext({
    tenant_id: 'acme-corp',
    application: 'order-processing',
    environment: 'production',
    workflow_id: 'order-fulfillment-v2',
    run_id: 'run-order-67890'
  });

  console.log('Root Context (Operation 1: Validate Order):');
  console.log('  correlation_id:', rootContext.correlation_id);
  console.log('  workflow_id:', rootContext.workflow_id);
  console.log('  run_id:', rootContext.run_id);
  console.log('  span_id:', rootContext.span_id || 'N/A');
  console.log('  parent_span_id:', rootContext.parent_span_id || 'N/A');

  // Create child context for nested operation
  const childContext1 = ContextManager.propagate(rootContext, {
    metadata: { operation: 'check_inventory' }
  });

  console.log('\nChild Context 1 (Operation 2: Check Inventory):');
  console.log('  correlation_id:', childContext1.correlation_id);
  console.log('  span_id:', childContext1.span_id);
  console.log('  parent_span_id:', childContext1.parent_span_id);
  console.log('  Same correlation_id:', childContext1.correlation_id === rootContext.correlation_id);

  // Create another child context
  const childContext2 = ContextManager.propagate(rootContext, {
    metadata: { operation: 'calculate_shipping' }
  });

  console.log('\nChild Context 2 (Operation 3: Calculate Shipping):');
  console.log('  correlation_id:', childContext2.correlation_id);
  console.log('  span_id:', childContext2.span_id);
  console.log('  parent_span_id:', childContext2.parent_span_id);
  console.log('  Same correlation_id:', childContext2.correlation_id === rootContext.correlation_id);

  // Create grandchild context
  const grandchildContext = ContextManager.propagate(childContext1, {
    metadata: { operation: 'reserve_stock' }
  });

  console.log('\nGrandchild Context (Operation 4: Reserve Stock):');
  console.log('  correlation_id:', grandchildContext.correlation_id);
  console.log('  span_id:', grandchildContext.span_id);
  console.log('  parent_span_id:', grandchildContext.parent_span_id);
  console.log('  Parent is child1:', grandchildContext.parent_span_id === childContext1.span_id);

  console.log('\nSpan Hierarchy:');
  console.log('   Root (Validate Order)');
  console.log('   ├── Child 1 (Check Inventory)');
  console.log('   │   └── Grandchild (Reserve Stock)');
  console.log('   └── Child 2 (Calculate Shipping)');
  console.log('\n   All operations share the same correlation_id');
  console.log('   Span hierarchy enables detailed operation tracing');
}

/**
 * Example 8: Session-Based Tracing
 * 
 * Shows how to use session_id to track multi-request conversational sessions.
 */
async function example8_SessionBasedTracing() {
  console.log('\n=== Example 8: Session-Based Tracing ===\n');

  const sessionId = 'session-conversation-789';

  console.log('Tracking conversation session:', sessionId);

  // Request 1: Initial message
  const request1Context = ContextManager.createContext({
    session_id: sessionId,
    tenant_id: 'acme-corp',
    application: 'chatbot',
    environment: 'production',
    user_id: 'user-alice'
  });

  console.log('\nRequest 1 (Initial Message):');
  console.log('  correlation_id:', request1Context.correlation_id);
  console.log('  session_id:', request1Context.session_id);

  // Request 2: Follow-up message (same session, different correlation_id)
  const request2Context = ContextManager.createContext({
    session_id: sessionId,
    tenant_id: 'acme-corp',
    application: 'chatbot',
    environment: 'production',
    user_id: 'user-alice'
  });

  console.log('\nRequest 2 (Follow-up Message):');
  console.log('  correlation_id:', request2Context.correlation_id);
  console.log('  session_id:', request2Context.session_id);
  console.log('  Different correlation_id:', request2Context.correlation_id !== request1Context.correlation_id);
  console.log('  Same session_id:', request2Context.session_id === request1Context.session_id);

  // Request 3: Another follow-up
  const request3Context = ContextManager.createContext({
    session_id: sessionId,
    tenant_id: 'acme-corp',
    application: 'chatbot',
    environment: 'production',
    user_id: 'user-alice'
  });

  console.log('\nRequest 3 (Another Follow-up):');
  console.log('  correlation_id:', request3Context.correlation_id);
  console.log('  session_id:', request3Context.session_id);

  console.log('\nSession-Based Tracing:');
  console.log('   Query: SELECT * FROM audit_events WHERE session_id =', sessionId);
  console.log('   Result: All 3 requests in the conversation');
  console.log('   Use case: Conversational AI, multi-turn interactions');
  console.log('   Each request has unique correlation_id, shared session_id');
}

/**
 * Example 9: Workflow and Run Tracking
 * 
 * Shows how to use workflow_id and run_id for governance-grade aggregation
 * and workflow-level reporting.
 */
async function example9_WorkflowAndRunTracking() {
  console.log('\n=== Example 9: Workflow and Run Tracking ===\n');

  const workflowId = 'customer-onboarding-v3';
  const runId = 'run-onboard-2024-001';

  console.log('Workflow Execution:');
  console.log('  workflow_id:', workflowId);
  console.log('  run_id:', runId);

  // Step 1: Validate customer data
  const step1Context = ContextManager.createContext({
    workflow_id: workflowId,
    run_id: runId,
    tenant_id: 'acme-corp',
    application: 'onboarding',
    environment: 'production',
    metadata: { step: 'validate_customer_data' }
  });

  console.log('\nStep 1: Validate Customer Data');
  console.log('  correlation_id:', step1Context.correlation_id);
  console.log('  workflow_id:', step1Context.workflow_id);
  console.log('  run_id:', step1Context.run_id);

  // Step 2: Create account
  const step2Context = ContextManager.createContext({
    workflow_id: workflowId,
    run_id: runId,
    tenant_id: 'acme-corp',
    application: 'onboarding',
    environment: 'production',
    metadata: { step: 'create_account' }
  });

  console.log('\nStep 2: Create Account');
  console.log('  correlation_id:', step2Context.correlation_id);
  console.log('  workflow_id:', step2Context.workflow_id);
  console.log('  run_id:', step2Context.run_id);
  console.log('  Different correlation_id:', step2Context.correlation_id !== step1Context.correlation_id);
  console.log('  Same run_id:', step2Context.run_id === step1Context.run_id);

  // Step 3: Send welcome email
  const step3Context = ContextManager.createContext({
    workflow_id: workflowId,
    run_id: runId,
    tenant_id: 'acme-corp',
    application: 'onboarding',
    environment: 'production',
    metadata: { step: 'send_welcome_email' }
  });

  console.log('\nStep 3: Send Welcome Email');
  console.log('  correlation_id:', step3Context.correlation_id);
  console.log('  workflow_id:', step3Context.workflow_id);
  console.log('  run_id:', step3Context.run_id);

  console.log('\nWorkflow and Run Tracking:');
  console.log('   Query by workflow: SELECT * FROM audit_events WHERE workflow_id =', workflowId);
  console.log('   Query by run: SELECT * FROM audit_events WHERE run_id =', runId);
  console.log('   Use case: Workflow-level reporting, compliance evidence bundles');
  console.log('   Each step has unique correlation_id, shared workflow_id and run_id');
}


/**
 * Best Practices Summary
 */
function printBestPractices() {
  console.log('\n' + '='.repeat(70));
  console.log('  Correlation IDs and Tracing - Best Practices');
  console.log('='.repeat(70) + '\n');

  console.log('1. Always Use ExecutionContext');
  console.log('   - Create context at the entry point of your application');
  console.log('   - Pass context to all TealTiger components');
  console.log('   - Auto-generation provides backwards compatibility\n');

  console.log('2. Propagate Context Across Service Boundaries');
  console.log('   - Use toHeaders() to convert context to HTTP headers');
  console.log('   - Use fromHeaders() to extract context from incoming requests');
  console.log('   - Preserve correlation_id across all services\n');

  console.log('3. Use Appropriate ID Scopes');
  console.log('   - correlation_id: Unique per request (required)');
  console.log('   - session_id: Shared across multi-request conversations');
  console.log('   - workflow_id: Shared across workflow executions');
  console.log('   - run_id: Unique per workflow execution instance');
  console.log('   - span_id: Unique per operation within a request\n');

  console.log('4. Integrate with Observability Tools');
  console.log('   - Use trace_id for OpenTelemetry integration');
  console.log('   - Use span_id and parent_span_id for operation hierarchy');
  console.log('   - Correlate TealTiger events with APM traces\n');

  console.log('5. Query Audit Logs Effectively');
  console.log('   - Query by correlation_id for single request traces');
  console.log('   - Query by session_id for conversation traces');
  console.log('   - Query by workflow_id for workflow-level reporting');
  console.log('   - Query by tenant_id for multi-tenant isolation\n');

  console.log('6. Enrich Context with Metadata');
  console.log('   - Add business context (user_id, tenant_id)');
  console.log('   - Add technical context (environment, application)');
  console.log('   - Add processing metadata (stage, metrics)');
  console.log('   - Use ContextManager.enrich() for incremental updates\n');

  console.log('7. Use Span Hierarchy for Complex Operations');
  console.log('   - Use ContextManager.propagate() for nested operations');
  console.log('   - Preserve correlation_id, generate new span_id');
  console.log('   - Set parent_span_id for operation lineage');
  console.log('   - Enable detailed operation tracing\n');

  console.log('8. Security and Compliance');
  console.log('   - correlation_id uses cryptographically random UUID v4');
  console.log('   - Never include sensitive data in correlation_id');
  console.log('   - Use audit redaction for sensitive content');
  console.log('   - Maintain immutable audit trails\n');
}

/**
 * Common Patterns Summary
 */
function printCommonPatterns() {
  console.log('\n' + '='.repeat(70));
  console.log('  Common Tracing Patterns');
  console.log('='.repeat(70) + '\n');

  console.log('Pattern 1: API Gateway with Downstream Services');
  console.log('  1. Extract context from incoming request headers');
  console.log('  2. Evaluate policies with context');
  console.log('  3. Convert context to headers for downstream calls');
  console.log('  4. All services share the same correlation_id\n');

  console.log('Pattern 2: Multi-Turn Conversational AI');
  console.log('  1. Create context with session_id for first message');
  console.log('  2. Generate new correlation_id for each message');
  console.log('  3. Preserve session_id across all messages');
  console.log('  4. Query audit logs by session_id for conversation history\n');

  console.log('Pattern 3: Workflow Orchestration');
  console.log('  1. Create context with workflow_id and run_id');
  console.log('  2. Generate new correlation_id for each step');
  console.log('  3. Preserve workflow_id and run_id across all steps');
  console.log('  4. Query audit logs by run_id for workflow execution trace\n');

  console.log('Pattern 4: Nested Operations with Span Hierarchy');
  console.log('  1. Create root context for top-level operation');
  console.log('  2. Use ContextManager.propagate() for child operations');
  console.log('  3. Each child gets new span_id, parent_span_id set');
  console.log('  4. Build operation tree for detailed tracing\n');

  console.log('Pattern 5: OpenTelemetry Integration');
  console.log('  1. Extract trace_id from OpenTelemetry span');
  console.log('  2. Include trace_id in ExecutionContext');
  console.log('  3. TealTiger events include trace_id');
  console.log('  4. Correlate security events with APM traces\n');
}

/**
 * Run all examples
 */
async function runAllExamples() {
  console.log('='.repeat(70));
  console.log('  TealTiger SDK v1.1.x - Correlation IDs & Tracing Examples');
  console.log('='.repeat(70));

  try {
    await example1_AutoGeneratedCorrelationId();
    await example2_CustomCorrelationId();
    await example3_ContextPropagation();
    await example4_QueryAuditLogsByCorrelationId();
    await example5_OpenTelemetryIntegration();
    await example6_HTTPHeaderPropagation();
    await example7_NestedOperationsWithSpans();
    await example8_SessionBasedTracing();
    await example9_WorkflowAndRunTracking();
    
    printBestPractices();
    printCommonPatterns();

    console.log('='.repeat(70));
    console.log('  All Examples Completed Successfully!');
    console.log('='.repeat(70) + '\n');
  } catch (error) {
    console.error('\nError running examples:', error);
    process.exit(1);
  }
}

// Run examples if this file is executed directly
if (require.main === module) {
  runAllExamples();
}

export {
  example1_AutoGeneratedCorrelationId,
  example2_CustomCorrelationId,
  example3_ContextPropagation,
  example4_QueryAuditLogsByCorrelationId,
  example5_OpenTelemetryIntegration,
  example6_HTTPHeaderPropagation,
  example7_NestedOperationsWithSpans,
  example8_SessionBasedTracing,
  example9_WorkflowAndRunTracking
};
